/* Generated by AN DISI Unibo */ 
package it.unibo.fridge_dummy

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Fridge_dummy ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('sysRules.pl')","") //set resVar	
						solve("consult('fridgeModel.pl')","") //set resVar	
						solve("consult('presenza.pl')","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitQuery", cond=doswitch() )
				}	 
				state("waitQuery") { //this:State
					action { //it:State
					}
					 transition(edgeName="t00",targetState="replyQuery",cond=whenDispatch("queryPresence"))
				}	 
				state("replyQuery") { //this:State
					action { //it:State
						delay(2000) 
						if( checkMsgContent( Term.createTerm("queryPresence(CATEGORY,NAME)"), Term.createTerm("queryPresence(CATEGORY,NAME)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								storeCurrentMessageForReply()
								solve("assert(done(queryReply,${payloadArg(1)}))","") //set resVar	
								solve("presenza(${payloadArg(1)},cibo,frigo)","") //set resVar	
								if(currentSolution.isSuccess()) { replyToCaller("replyPresence", "replyPresence(present)")
								 }
								else
								{ replyToCaller("replyPresence", "replyPresence(absent)")
								 }
						}
					}
					 transition( edgeName="goto",targetState="waitQuery", cond=doswitch() )
				}	 
			}
		}
}
