/* Generated by AN DISI Unibo */ 
package it.unibo.butler

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Butler ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var sync = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('sysRules.pl')","") //set resVar	
						solve("consult('butlerModel.pl')","") //set resVar	
						solve("consult('test.pl')","") //set resVar	
						solve("consult('locationIndex.pl')","") //set resVar	
						solve("showResourceModel","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						itunibo.butler.butlerResourceModelSupport.updateModelState(myself ,"waitCmd" )
						solve("showResourceModel","") //set resVar	
					}
					 transition(edgeName="t00",targetState="solveCmd",cond=whenDispatch("cmd"))
				}	 
				state("solveCmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("cmd(CMD,ARG1)"), Term.createTerm("cmd(CMD,ARG1)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								itunibo.butler.butlerResourceModelSupport.updateModelState(myself ,"solveCmd" )
								solve("retract(currentCmd(_,_))","") //set resVar	
								solve("assert(currentCmd(${payloadArg(0)},${payloadArg(1)}))","") //set resVar	
								solve("comando(${payloadArg(0)},${payloadArg(1)})","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="solveAction", cond=doswitch() )
				}	 
				state("solveAction") { //this:State
					action { //it:State
						itunibo.butler.butlerResourceModelSupport.updateModelState(myself ,"solveAction" )
						solve("retract(azione(ARG0,ARG1,ARG2,ARG3))","") //set resVar	
						if(currentSolution.isSuccess()){ val Azione= currentSolution.getVarValue("ARG0").toString()
						if(Azione=="movimento"){ val Destinazione= getCurSol("ARG1").toString()
						forward("movimento", "movimento($Destinazione)" ,"butler" ) 
						 }
						if(Azione=="check"){ println("hello3")
						val Check= getCurSol("ARG1").toString()
						forward("check", "check($Check)" ,"butler" ) 
						 }
						 }
						else
						 { forward("done", "done" ,"butler" ) 
						  }
					}
					 transition(edgeName="t01",targetState="waitCmd",cond=whenDispatch("done"))
					transition(edgeName="t02",targetState="azioneMovimento",cond=whenDispatch("movimento"))
					transition(edgeName="t03",targetState="azioneCheck",cond=whenDispatch("check"))
					transition(edgeName="t04",targetState="stoppedSolvedAction",cond=whenEvent("stopAppl"))
				}	 
				state("azioneMovimento") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("movimento(DESTINAZIONE)"), Term.createTerm("movimento(DESTINAZIONE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("$name in ${currentState.stateName} | $currentMsg")
								solve("location(${payloadArg(0)},X,Y)","") //set resVar	
								val X= getCurSol("X").toString()
								val Y= getCurSol("Y").toString()
								solve("assert(movingTo(${payloadArg(0)}))","") //set resVar	
								forward("setGoal", "setGoal($X,$Y)" ,"pathfinder" ) 
						}
					}
					 transition(edgeName="t05",targetState="assertMove",cond=whenDispatch("goalReached"))
				}	 
				state("assertMove") { //this:State
					action { //it:State
						solve("retract(movingTo(DEST))","") //set resVar	
						val Dest= getCurSol("DEST")
						solve("assert(done(movimento,$Dest))","") //set resVar	
					}
					 transition( edgeName="goto",targetState="solveAction", cond=doswitch() )
				}	 
				state("azioneCheck") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("check(ARG1)"), Term.createTerm("check(ARG1)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								solve("assert(done(check,${payloadArg(0)}))","") //set resVar	
						}
					}
					 transition( edgeName="goto",targetState="solveAction", cond=doswitch() )
				}	 
				state("stoppedSolvedAction") { //this:State
					action { //it:State
						itunibo.butler.butlerResourceModelSupport.updateModelState(myself ,"stoppedSolvedAction" )
						println("$name in ${currentState.stateName} | $currentMsg")
						solve("showResourceModel","") //set resVar	
					}
					 transition(edgeName="t06",targetState="restartSolvedAction",cond=whenEvent("reactivateAppl"))
				}	 
				state("restartSolvedAction") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						solve("showResourceModel","") //set resVar	
					}
					 transition(edgeName="t07",targetState="waitCmd",cond=whenDispatch("done"))
					transition(edgeName="t08",targetState="stoppedSolvedAction",cond=whenEvent("stopAppl"))
				}	 
			}
		}
}
